spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-db
    username: root
    password: "!i@b#o"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: order-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka